# Generated by Django 6.0.2 on 2026-04-26 07:16

import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(db_index=True, default=projects.models.generate_slug, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='original_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug', 'created_at'], name='projects_pr_slug_3738af_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'created_at'], name='projects_pr_user_id_29bec8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project', 'uploaded_at'], name='projects_pr_project_01c624_idx'),
        ),
    ]
