# Generated by Django 6.0.2 on 2026-06-16 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_alter_projectfile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('project_name', models.CharField(default='desconocido', max_length=255, verbose_name='Nombre del Proyecto')),
                ('file_count', models.IntegerField(default=0, verbose_name='Archivos Procesados')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Extracción')),
            ],
            options={
                'verbose_name': 'Registro de Extracción',
                'verbose_name_plural': 'Registros de Extracción',
                'ordering': ['-created_at'],
            },
        ),
    ]
