# Generated by Django 6.0.2 on 2026-06-16 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_extractionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractionlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Extracción Anónima', 'verbose_name_plural': 'Historial de Uso'},
        ),
        migrations.RemoveField(
            model_name='extractionlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='extractionlog',
            name='project_name',
        ),
    ]
