# Generated by Django 6.0.6 on 2026-06-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_extractionlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_extractions', models.IntegerField(default=0, verbose_name='Total de Proyectos Procesados')),
            ],
            options={
                'verbose_name': 'Contador Global',
                'verbose_name_plural': 'Contador Global',
            },
        ),
        migrations.DeleteModel(
            name='ExtractionLog',
        ),
    ]
