# Generated by Django 6.0.2 on 2026-06-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_globalcounter_delete_extractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(max_length=500, upload_to='projects/%Y/%m/%d/'),
        ),
    ]
