# Generated by Django 6.0.2 on 2026-02-18 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=10)),
                ('sintomas', models.TextField()),
                ('diagnostico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_arterial', models.CharField(max_length=20)),
                ('frecuencia_cardiaca', models.PositiveIntegerField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('saturacion_oxigeno', models.DecimalField(decimal_places=1, max_digits=4)),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='pacientes.paciente')),
            ],
        ),
    ]
