# Generated by Django 6.0.2 on 2026-02-18 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RitmoCardiaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ritmo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ritmo_cardiaco', to='pacientes.paciente')),
                ('signos_vitales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ritmo_cardiaco', to='pacientes.signosvitales')),
            ],
        ),
    ]
