# Generated by Django 6.0.2 on 2026-02-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_ritmocardiaco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='diagnostico',
            new_name='diagnóstico_presuntivo',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='genero',
            new_name='sexo',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='sintomas',
            new_name='signos_y_síntomas',
        ),
    ]
