# Generated by Django 6.0.2 on 2026-02-24 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_diagnostico_paciente_diagnóstico_presuntivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritmocardiaco',
            name='dolor_sedacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ritmocardiaco',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ritmocardiaco',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ritmocardiaco',
            name='glasgow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ritmocardiaco',
            name='pam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ritmocardiaco',
            name='presion_arterial_diastolica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ritmocardiaco',
            name='presion_arterial_sistolica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ritmocardiaco',
            name='ritmo_cardiaco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ritmocardiaco',
            name='spo2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ritmocardiaco',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Monitorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorizaciones', to='pacientes.paciente')),
            ],
        ),
    ]
