# Generated by Django 6.0.2 on 2026-02-24 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_ritmocardiaco_dolor_sedacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscenarioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='dolor_sedacion',
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='frecuencia_cardiaca',
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='frecuencia_respiratoria',
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='glasgow',
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='pam',
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='presion_arterial_diastolica',
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='presion_arterial_sistolica',
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='ritmo_cardiaco',
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='spo2',
        ),
        migrations.RemoveField(
            model_name='ritmocardiaco',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='dolor_sedacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='glasgow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='pam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='presion_arterial_diastolica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='presion_arterial_sistolica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='ritmo_cardiaco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='spo2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EtapaEscenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('presion_arterial_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_arterial_diastolica', models.IntegerField(blank=True, null=True)),
                ('pam', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('glasgow', models.IntegerField(blank=True, null=True)),
                ('dolor_sedacion', models.CharField(blank=True, max_length=50, null=True)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='pacientes.escenarioclinico')),
            ],
        ),
    ]
