# Generated by Django 6.0.2 on 2026-02-25 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_escenarioclinico_remove_ritmocardiaco_dolor_sedacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('evaluacion', 'Evaluación'), ('terapeutica', 'Terapéutica'), ('comunicacion', 'Comunicación/Escala'), ('confirmacion', 'Confirmación/Registro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('realizada_por', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='pacientes.paciente')),
            ],
        ),
    ]
