# Generated by Django 6.0.2 on 2026-02-25 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_intervencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencion',
            name='escenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='pacientes.escenarioclinico'),
        ),
        migrations.AddField(
            model_name='intervencion',
            name='monitorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='pacientes.monitorizacion'),
        ),
    ]
