# Generated by Django 6.0.2 on 2026-02-25 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_intervencion_escenario_intervencion_monitorizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('puntaje', models.PositiveIntegerField(default=0)),
                ('checklist', models.TextField()),
                ('errores', models.TextField()),
                ('omisiones', models.TextField()),
                ('competencias', models.TextField()),
                ('debriefing', models.TextField()),
                ('escenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='pacientes.escenarioclinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='pacientes.paciente')),
            ],
        ),
    ]
