# Generated by Django 6.0.2 on 2026-02-25 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorizacion',
            name='signos_vitales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.signosvitales'),
        ),
        migrations.AddField(
            model_name='monitorizacion',
            name='tipo_ritmo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monitorizacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='monitorizacion',
            name='ritmo_cardiaco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.ritmocardiaco'),
        ),
    ]
