# Generated by Django 6.0.2 on 2026-02-25 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_monitorizacion_signos_vitales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escenarioclinico',
            name='etapa_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenarios_actuales', to='pacientes.etapaescenario'),
        ),
        migrations.AddField(
            model_name='escenarioclinico',
            name='modo_instructor',
            field=models.BooleanField(default=False, help_text='¿Permitir avance manual por docente?'),
        ),
        migrations.AddField(
            model_name='etapaescenario',
            name='avance_por_intervencion',
            field=models.BooleanField(default=False, help_text='¿Avanza por intervención?'),
        ),
        migrations.AddField(
            model_name='etapaescenario',
            name='duracion_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración de la etapa en segundos', null=True),
        ),
    ]
